version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cc
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  c2-server:
    build:
      context: ./c2-server
    container_name: c2-server
    ports:
      - '8081:80'
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: cc
      DB_USER: root
      DB_PASSWORD: root
      WS_URL: ws://web-socket:8080

  web-socket:
    build:
      context: ./web-socket
    container_name: web-socket
    ports:
      - '8082:8080'  # Change to the WebSocket port
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: cc
      DB_USER: root
      DB_PASSWORD: root

volumes:
  mysql_data:
